# Spring properties
spring:
  application:
     name: products-service
  datasource:
    platform: hsqldb

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
  